
"use client"

import { usePathname } from 'next/navigation'; 
import "../styles/globals.scss";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import CartProvider from "@/components/CartContext/CartContext";
import { SearchProvider } from "../components/SearchContext/SearchContext";
import { WishlistProvider } from "../components/WishlistContext/WishlistContext";
import { SessionProvider } from "next-auth/react";

//  export const metadata: Metadata = {
//   title: "Gymbeast",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname();

  const isLoginPage = pathname === '/login'
  const isRegisterPage = pathname === '/register'


  return (
    <html lang="en">
      <body>
        <SessionProvider>
        <CartProvider>
          <SearchProvider>
            <WishlistProvider>
              {!isLoginPage && !isRegisterPage && <Header />}
              {children}
              {!isLoginPage && !isRegisterPage && <Footer />}
            </WishlistProvider>
          </SearchProvider>
        </CartProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
